-- This module is the root of the PAdicLanglandsCanonicalLaneLean Lean proof package.
import PAdicLanglandsCanonicalLaneLean.Basic
import PAdicLanglandsCanonicalLaneLean.SourcePackage
import PAdicLanglandsCanonicalLaneLean.SourceDependencies
import PAdicLanglandsCanonicalLaneLean.Formalization
import PAdicLanglandsCanonicalLaneLean.ReviewerBridge
import PAdicLanglandsCanonicalLaneLean.TheoremStatement
import PAdicLanglandsCanonicalLaneLean.MathlibObjects
import PAdicLanglandsCanonicalLaneLean.AdmissibleClass
import PAdicLanglandsCanonicalLaneLean.Projection
import PAdicLanglandsCanonicalLaneLean.BridgeLemmas
import PAdicLanglandsCanonicalLaneLean.GateLemmas
import PAdicLanglandsCanonicalLaneLean.FinalTheorem
import PAdicLanglandsCanonicalLaneLean.MathlibStatement
